### PR TITLE
Added gulp build to create dist files

### PR DESCRIPTION
**Pull request by Grafikart**
I wanted to use crevasse but manually injecting dependencies in the <head> can be boring

I created a gulp file to build 2 min in the dist folder.
- crevasse.min.js
- crevasse.full.min js, contains all dependencies except jQuery

I can improve the task to compile the file from the coffe but since that was done by the CakeFile I did not implemented that.

### CODE REVIEW

**Comment by patbenatar** [comment]
@Grafikart Thanks for taking the time to put this together. I think we should choose either gulp or Cakefile, and port everything into one. I'm OK with going the gulp route if you have some time to port the existing build and dev workflow from the Cakefile. What do you think?

**Comment by patbenatar** [comment]
Also as a part of this we should update the README to include how to use this package and how to build using the new workflow

**Comment by Grafikart** [comment]
Right I did that on a branch I can commit edits. I'll try to improve the gulpfile to make it works like the cakefile. Do you want to keep the thing that tag the commits ?

**Comment by patbenatar** [comment]
@Grafikart Yeah if we can keep all the Cakefile functionality that'd be great. git tagging is nice for doing versioned releases and being able to easily get back to any version to hotfix

**Comment by patbenatar** [comment]
Thanks for your help!

**Pull request closed without merging**
